spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  #    non-secure-port: 8081
  #    status-page-url: http://localhost:8081
  #    health-check-url: http://localhost:8081/actuator/health
  #    home-page-url: http://localhost:8081/

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
